server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://3.71.11.3:8542/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect